# Generated by Django 4.1.2 on 2022-10-24 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_address_city_city_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.city', verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CityAndStreet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_rel', to='shop.address', verbose_name='Адрес')),
                ('city_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_rel', to='shop.city', verbose_name='Город')),
            ],
        ),
    ]
