# Generated by Django 4.1.2 on 2022-10-25 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_city_address_address_address_cityandstreet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_rel', to='shop.city', verbose_name='Город'),
        ),
        migrations.DeleteModel(
            name='CityAndStreet',
        ),
    ]
