# Generated by Django 4.1.2 on 2022-10-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_city_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='address',
        ),
        migrations.AddField(
            model_name='city',
            name='address',
            field=models.ManyToManyField(related_name='address_rel', to='shop.address', verbose_name='Улица'),
        ),
    ]
