# Generated by Django 4.1.2 on 2022-10-25 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_city_address_cityandaddress_city_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityandaddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_c', to='shop.address', verbose_name='Улица'),
        ),
    ]
