# Generated by Django 4.1.2 on 2022-10-25 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_address_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Street',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='address',
        ),
        migrations.AddField(
            model_name='shop',
            name='street',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address_shop', to='shop.street', verbose_name='Улица'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_shop', to='shop.city', verbose_name='Город'),
        ),
    ]
